### ISSUE TITLE
add type hints

### ISSUE THREAD

**Issue by HitLuca** [metabolize/env-flag#21]
When using this library, mypy complains that the env_flag package doesn't have type hints or stubs.
```python
my_project.py:14: error: Skipping analyzing 'env_flag': found module but no type hints or library stubs
```

I believe you only need two type hints in the `env_flag` function, resulting in

```python
def env_flag(env_var: str, default=False) -> bool:
```

I am not 100% sure on this, but it's probably the only thing needed for this project to be correctly analyzed by mypy.

I didn't make a PR as it's probably much quicker for the owner to make this change instead of doing the fork-setup-edit-pr pipeline

**Comment by paulmelnikow** [comment]
Hi! I don’t use mypy though I’d be glad to include this.

Is there a way to test that the type hints are correct? For TypeScript there is a program called dtslint which helps with that.

**Comment by HitLuca** [comment]
I made a PR that adds the type hints. It should work without issues, tested on a local project but better if you give it a quick test also!
